### ISSUE TITLE
Cannot execute system test as it cannot load extension for eventamchine

### ISSUE THREAD

**Issue by mookjp** [mookjp/pool#131]
I have seen [the issue; problem with Ruby 2.1.0 on eventmachine](https://github.com/eventmachine/eventmachine/issues/504) and one says that `eventmachine 1.0.4` resolves this problem.

logs:

```sh
==> default: Step 16 : RUN /opt/ruby-2.1.2/bin/bundle exec rake spec
==> default:  ---> Running in a5a60912b77d
==> default: /opt/ruby-2.1.2/bin/ruby -I/tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib:/tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-support-3.1.2/lib /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
==> default: Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
==> default:
==> default: /tmp/builder/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:8:in `require': cannot load such file -- rubyeventmachine (LoadError)
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:8:in `<top (required)>'
==> default:
==> default:    from /tmp/builder/lib/builder/build_handler.rb:1:in `require'
==> default:
==> default:    from /tmp/builder/lib/builder/build_handler.rb:1:in `<top (required)>'
==> default:
==> default:    from /tmp/builder/lib/builder.rb:9:in `require'
==> default:
==> default:    from /tmp/builder/lib/builder.rb:9:in `<top (required)>'
==> default:
==> default:    from /tmp/builder/spec/builder/builder/git_handler_spec.rb:3:in `require'
==> default:
==> default:    from /tmp/builder/spec/builder/builder/git_handler_spec.rb:3:in `<top (required)>'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
==> default:
==> default:    from /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<main>'
==> default:
==> default: Coverage report generated for RSpec to /tmp/builder/coverage. 33 / 195 LOC (16.92%) covered.
==> default: /opt/ruby-2.1.2/bin/ruby -I/tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib:/tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-support-3.1.2/lib /tmp/builder/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
==> default:
==> default: time="2015-01-19T00:43:40Z" level="info" msg="The command [/bin/sh -c /opt/ruby-2.1.2/bin/bundle exec rake spec] returned a non-zero code: 1"
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by ainoya** [comment]
Today I tried to reproduce this bug on newly cloned repository, but I couldn't see it...

**Comment by mookjp** [comment]
@ainoya I found that there's `docker/pool/builder/vendor`. After deleting `vendor`, it does not say this error. It may be caused by my local environment only.
I'm sorry for confusing you.
